// Generated by rstantools.  Do not edit by hand.

/*
    BMABMDR is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    BMABMDR is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with BMABMDR.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#ifndef USE_STANC3
#define USE_STANC3
#endif
#include <rstan/rstaninc.hpp>
// Code generated by stanc v2.26.1-4-gd72b68b7-dirty
#include <stan/model/model_header.hpp>
namespace model_mG4c_namespace {
inline void validate_positive_index(const char* var_name, const char* expr,
                                    int val) {
  if (val < 1) {
    std::stringstream msg;
    msg << "Found dimension size less than one in simplex declaration"
        << "; variable=" << var_name << "; dimension size expression=" << expr
        << "; expression value=" << val;
    std::string msg_str(msg.str());
    throw std::invalid_argument(msg_str.c_str());
  }
}
inline void validate_unit_vector_index(const char* var_name, const char* expr,
                                       int val) {
  if (val <= 1) {
    std::stringstream msg;
    if (val == 1) {
      msg << "Found dimension size one in unit vector declaration."
          << " One-dimensional unit vector is discrete"
          << " but the target distribution must be continuous."
          << " variable=" << var_name << "; dimension size expression=" << expr;
    } else {
      msg << "Found dimension size less than one in unit vector declaration"
          << "; variable=" << var_name << "; dimension size expression=" << expr
          << "; expression value=" << val;
    }
    std::string msg_str(msg.str());
    throw std::invalid_argument(msg_str.c_str());
  }
}
using std::istream;
using std::string;
using std::stringstream;
using std::vector;
using std::pow;
using stan::io::dump;
using stan::math::lgamma;
using stan::model::model_base_crtp;
using stan::model::rvalue;
using stan::model::cons_list;
using stan::model::index_uni;
using stan::model::index_max;
using stan::model::index_min;
using stan::model::index_min_max;
using stan::model::index_multi;
using stan::model::index_omni;
using stan::model::nil_index_list;
using namespace stan::math;
using stan::math::pow; 
stan::math::profile_map profiles__;
static int current_statement__= 0;
static const std::vector<string> locations_array__ = {" (found before start of program)",
                                                      " (in 'string', line 66, column 2 to column 21)",
                                                      " (in 'string', line 67, column 2 to column 30)",
                                                      " (in 'string', line 68, column 2 to column 38)",
                                                      " (in 'string', line 69, column 2 to column 47)",
                                                      " (in 'string', line 70, column 2 to column 12)",
                                                      " (in 'string', line 71, column 2 to column 12)",
                                                      " (in 'string', line 72, column 2 to column 12)",
                                                      " (in 'string', line 75, column 2 to column 9)",
                                                      " (in 'string', line 76, column 2 to column 9)",
                                                      " (in 'string', line 77, column 2 to column 9)",
                                                      " (in 'string', line 78, column 2 to column 12)",
                                                      " (in 'string', line 79, column 2 to column 9)",
                                                      " (in 'string', line 80, column 2 to column 9)",
                                                      " (in 'string', line 81, column 2 to column 14)",
                                                      " (in 'string', line 82, column 2 to column 17)",
                                                      " (in 'string', line 83, column 2 to column 12)",
                                                      " (in 'string', line 84, column 2 to column 18)",
                                                      " (in 'string', line 85, column 2 to column 20)",
                                                      " (in 'string', line 86, column 2 to column 18)",
                                                      " (in 'string', line 87, column 2 to column 19)",
                                                      " (in 'string', line 88, column 2 to column 21)",
                                                      " (in 'string', line 89, column 2 to column 14)",
                                                      " (in 'string', line 93, column 4 to column 26)",
                                                      " (in 'string', line 92, column 44 to line 94, column 3)",
                                                      " (in 'string', line 92, column 8 to line 94, column 3)",
                                                      " (in 'string', line 91, column 4 to column 13)",
                                                      " (in 'string', line 90, column 38 to line 92, column 3)",
                                                      " (in 'string', line 90, column 2 to line 94, column 3)",
                                                      " (in 'string', line 98, column 4 to column 36)",
                                                      " (in 'string', line 97, column 25 to line 99, column 3)",
                                                      " (in 'string', line 97, column 8 to line 99, column 3)",
                                                      " (in 'string', line 96, column 4 to column 25)",
                                                      " (in 'string', line 95, column 19 to line 97, column 3)",
                                                      " (in 'string', line 95, column 2 to line 99, column 3)",
                                                      " (in 'string', line 100, column 2 to column 21)",
                                                      " (in 'string', line 104, column 4 to column 46)",
                                                      " (in 'string', line 103, column 44 to line 105, column 3)",
                                                      " (in 'string', line 103, column 8 to line 105, column 3)",
                                                      " (in 'string', line 102, column 4 to column 20)",
                                                      " (in 'string', line 101, column 38 to line 103, column 3)",
                                                      " (in 'string', line 101, column 2 to line 105, column 3)",
                                                      " (in 'string', line 106, column 2 to column 16)",
                                                      " (in 'string', line 107, column 2 to column 16)",
                                                      " (in 'string', line 108, column 2 to column 22)",
                                                      " (in 'string', line 109, column 3 to column 21)",
                                                      " (in 'string', line 110, column 3 to column 16)",
                                                      " (in 'string', line 111, column 3 to column 16)",
                                                      " (in 'string', line 112, column 3 to column 16)",
                                                      " (in 'string', line 113, column 3 to column 23)",
                                                      " (in 'string', line 114, column 3 to column 101)",
                                                      " (in 'string', line 115, column 3 to column 16)",
                                                      " (in 'string', line 118, column 2 to column 65)",
                                                      " (in 'string', line 119, column 2 to column 65)",
                                                      " (in 'string', line 120, column 2 to column 65)",
                                                      " (in 'string', line 121, column 46 to column 52)",
                                                      " (in 'string', line 121, column 2 to column 54)",
                                                      " (in 'string', line 122, column 2 to column 44)",
                                                      " (in 'string', line 123, column 2 to column 65)",
                                                      " (in 'string', line 155, column 4 to column 12)",
                                                      " (in 'string', line 156, column 4 to column 12)",
                                                      " (in 'string', line 158, column 4 to column 11)",
                                                      " (in 'string', line 159, column 4 to column 12)",
                                                      " (in 'string', line 160, column 4 to column 41)",
                                                      " (in 'string', line 161, column 4 to column 14)",
                                                      " (in 'string', line 163, column 4 to column 23)",
                                                      " (in 'string', line 164, column 17 to column 19)",
                                                      " (in 'string', line 164, column 6 to column 26)",
                                                      " (in 'string', line 165, column 17 to column 19)",
                                                      " (in 'string', line 165, column 6 to column 23)",
                                                      " (in 'string', line 166, column 13 to column 15)",
                                                      " (in 'string', line 166, column 17 to column 19)",
                                                      " (in 'string', line 166, column 6 to column 23)",
                                                      " (in 'string', line 167, column 13 to column 15)",
                                                      " (in 'string', line 167, column 17 to column 19)",
                                                      " (in 'string', line 167, column 6 to column 27)",
                                                      " (in 'string', line 168, column 6 to column 26)",
                                                      " (in 'string', line 169, column 6 to column 33)",
                                                      " (in 'string', line 175, column 12 to column 38)",
                                                      " (in 'string', line 174, column 15 to line 176, column 11)",
                                                      " (in 'string', line 173, column 12 to column 28)",
                                                      " (in 'string', line 172, column 24 to line 174, column 11)",
                                                      " (in 'string', line 172, column 10 to line 176, column 11)",
                                                      " (in 'string', line 171, column 24 to line 177, column 9)",
                                                      " (in 'string', line 171, column 8 to line 177, column 9)",
                                                      " (in 'string', line 170, column 22 to line 178, column 7)",
                                                      " (in 'string', line 170, column 6 to line 178, column 7)",
                                                      " (in 'string', line 179, column 6 to column 30)",
                                                      " (in 'string', line 180, column 6 to column 51)",
                                                      " (in 'string', line 181, column 6 to column 29)",
                                                      " (in 'string', line 182, column 4 to column 18)",
                                                      " (in 'string', line 162, column 18 to line 183, column 5)",
                                                      " (in 'string', line 162, column 4 to line 183, column 5)",
                                                      " (in 'string', line 157, column 17 to line 184, column 5)",
                                                      " (in 'string', line 157, column 4 to line 184, column 5)",
                                                      " (in 'string', line 154, column 44 to line 185, column 3)",
                                                      " (in 'string', line 154, column 8 to line 185, column 3)",
                                                      " (in 'string', line 125, column 4 to column 12)",
                                                      " (in 'string', line 126, column 4 to column 12)",
                                                      " (in 'string', line 128, column 4 to column 11)",
                                                      " (in 'string', line 129, column 4 to column 12)",
                                                      " (in 'string', line 130, column 4 to column 41)",
                                                      " (in 'string', line 131, column 4 to column 14)",
                                                      " (in 'string', line 133, column 4 to column 23)",
                                                      " (in 'string', line 134, column 17 to column 19)",
                                                      " (in 'string', line 134, column 6 to column 26)",
                                                      " (in 'string', line 135, column 17 to column 19)",
                                                      " (in 'string', line 135, column 6 to column 23)",
                                                      " (in 'string', line 136, column 13 to column 15)",
                                                      " (in 'string', line 136, column 17 to column 19)",
                                                      " (in 'string', line 136, column 6 to column 23)",
                                                      " (in 'string', line 137, column 13 to column 15)",
                                                      " (in 'string', line 137, column 17 to column 19)",
                                                      " (in 'string', line 137, column 6 to column 27)",
                                                      " (in 'string', line 138, column 6 to column 26)",
                                                      " (in 'string', line 139, column 6 to column 33)",
                                                      " (in 'string', line 145, column 12 to column 38)",
                                                      " (in 'string', line 144, column 15 to line 146, column 11)",
                                                      " (in 'string', line 143, column 12 to column 28)",
                                                      " (in 'string', line 142, column 24 to line 144, column 11)",
                                                      " (in 'string', line 142, column 10 to line 146, column 11)",
                                                      " (in 'string', line 141, column 24 to line 147, column 9)",
                                                      " (in 'string', line 141, column 8 to line 147, column 9)",
                                                      " (in 'string', line 140, column 22 to line 148, column 7)",
                                                      " (in 'string', line 140, column 6 to line 148, column 7)",
                                                      " (in 'string', line 149, column 6 to column 30)",
                                                      " (in 'string', line 150, column 6 to column 51)",
                                                      " (in 'string', line 151, column 4 to column 18)",
                                                      " (in 'string', line 132, column 18 to line 152, column 5)",
                                                      " (in 'string', line 132, column 4 to line 152, column 5)",
                                                      " (in 'string', line 127, column 17 to line 153, column 5)",
                                                      " (in 'string', line 127, column 4 to line 153, column 5)",
                                                      " (in 'string', line 124, column 38 to line 154, column 3)",
                                                      " (in 'string', line 124, column 2 to line 185, column 3)",
                                                      " (in 'string', line 37, column 2 to column 8)",
                                                      " (in 'string', line 38, column 8 to column 9)",
                                                      " (in 'string', line 38, column 2 to column 11)",
                                                      " (in 'string', line 39, column 2 to column 9)",
                                                      " (in 'string', line 40, column 2 to column 11)",
                                                      " (in 'string', line 41, column 2 to column 12)",
                                                      " (in 'string', line 42, column 10 to column 11)",
                                                      " (in 'string', line 42, column 13 to column 18)",
                                                      " (in 'string', line 42, column 2 to column 20)",
                                                      " (in 'string', line 43, column 9 to column 11)",
                                                      " (in 'string', line 43, column 13 to column 17)",
                                                      " (in 'string', line 43, column 2 to column 21)",
                                                      " (in 'string', line 44, column 9 to column 10)",
                                                      " (in 'string', line 44, column 2 to column 14)",
                                                      " (in 'string', line 45, column 2 to column 9)",
                                                      " (in 'string', line 46, column 2 to column 13)",
                                                      " (in 'string', line 47, column 2 to column 14)",
                                                      " (in 'string', line 48, column 2 to column 20)",
                                                      " (in 'string', line 49, column 2 to column 20)",
                                                      " (in 'string', line 50, column 2 to column 20)",
                                                      " (in 'string', line 51, column 2 to column 19)",
                                                      " (in 'string', line 52, column 2 to column 19)",
                                                      " (in 'string', line 53, column 2 to column 27)",
                                                      " (in 'string', line 54, column 2 to column 14)",
                                                      " (in 'string', line 55, column 2 to column 16)",
                                                      " (in 'string', line 56, column 2 to column 38)",
                                                      " (in 'string', line 57, column 2 to column 9)",
                                                      " (in 'string', line 58, column 2 to column 38)",
                                                      " (in 'string', line 59, column 2 to column 9)",
                                                      " (in 'string', line 62, column 3 to column 21)",
                                                      " (in 'string', line 63, column 3 to column 28)",
                                                      " (in 'string', line 68, column 23 to column 36)",
                                                      " (in 'string', line 69, column 32 to column 45)",
                                                      " (in 'string', line 85, column 9 to column 10)",
                                                      " (in 'string', line 86, column 9 to column 10)",
                                                      " (in 'string', line 6, column 3 to column 15)",
                                                      " (in 'string', line 7, column 3 to column 19)",
                                                      " (in 'string', line 8, column 3 to column 31)",
                                                      " (in 'string', line 20, column 27 to column 34)",
                                                      " (in 'string', line 20, column 11 to column 34)",
                                                      " (in 'string', line 19, column 21 to column 101)",
                                                      " (in 'string', line 19, column 6 to line 20, column 34)",
                                                      " (in 'string', line 18, column 31 to line 21, column 4)",
                                                      " (in 'string', line 18, column 9 to line 21, column 4)",
                                                      " (in 'string', line 17, column 28 to column 35)",
                                                      " (in 'string', line 17, column 12 to column 35)",
                                                      " (in 'string', line 16, column 22 to column 87)",
                                                      " (in 'string', line 16, column 7 to line 17, column 35)",
                                                      " (in 'string', line 15, column 31 to line 18, column 4)",
                                                      " (in 'string', line 15, column 9 to line 21, column 4)",
                                                      " (in 'string', line 14, column 28 to column 35)",
                                                      " (in 'string', line 14, column 12 to column 35)",
                                                      " (in 'string', line 13, column 22 to column 102)",
                                                      " (in 'string', line 13, column 7 to line 14, column 35)",
                                                      " (in 'string', line 12, column 31 to line 15, column 4)",
                                                      " (in 'string', line 12, column 9 to line 21, column 4)",
                                                      " (in 'string', line 11, column 28 to column 35)",
                                                      " (in 'string', line 11, column 12 to column 35)",
                                                      " (in 'string', line 10, column 22 to column 84)",
                                                      " (in 'string', line 10, column 7 to line 11, column 35)",
                                                      " (in 'string', line 9, column 25 to line 12, column 4)",
                                                      " (in 'string', line 9, column 3 to line 21, column 4)",
                                                      " (in 'string', line 22, column 3 to column 12)",
                                                      " (in 'string', line 5, column 26 to line 23, column 4)",
                                                      " (in 'string', line 25, column 4 to column 12)",
                                                      " (in 'string', line 26, column 4 to column 12)",
                                                      " (in 'string', line 27, column 4 to column 12)",
                                                      " (in 'string', line 28, column 4 to column 12)",
                                                      " (in 'string', line 29, column 4 to column 39)",
                                                      " (in 'string', line 30, column 4 to column 38)",
                                                      " (in 'string', line 31, column 4 to column 41)",
                                                      " (in 'string', line 32, column 4 to column 28)",
                                                      " (in 'string', line 33, column 4 to column 31)",
                                                      " (in 'string', line 24, column 74 to line 34, column 3)"};
template <typename T0__, typename T1__, typename T2__>
Eigen::Matrix<stan::promote_args_t<stan::value_type_t<T0__>, stan::value_type_t<T1__>,
T2__>, -1, 1>
algebra_system(const T0__& y_est_arg__, const T1__& theta_arg__,
               const std::vector<T2__>& x_r, const std::vector<int>& x_i,
               std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<stan::value_type_t<T0__>,
          stan::value_type_t<T1__>,
          T2__>;
  const auto& y_est = to_ref(y_est_arg__);
  const auto& theta = to_ref(theta_arg__);
  const static bool propto__ = true;
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  (void) DUMMY_VAR__;  // suppress unused var warning
  
  try {
    Eigen::Matrix<local_scalar_t__, -1, 1> x;
    x = Eigen::Matrix<local_scalar_t__, -1, 1>(1);
    stan::math::fill(x, DUMMY_VAR__);
    
    local_scalar_t__ q;
    q = DUMMY_VAR__;
    
    current_statement__ = 170;
    q = x_r[(1 - 1)];
    local_scalar_t__ data_ty_estpe;
    data_ty_estpe = DUMMY_VAR__;
    
    current_statement__ = 171;
    data_ty_estpe = x_i[(1 - 1)];
    current_statement__ = 195;
    if (logical_eq(data_ty_estpe, 1)) {
      current_statement__ = 193;
      if (logical_gt(y_est[(1 - 1)], 0)) {
        current_statement__ = 192;
        assign(x, cons_list(index_uni(1), nil_index_list()),
          (gamma_p(theta[(3 - 1)], (y_est[(1 - 1)] * theta[(1 - 1)])) -
            (q / (theta[(2 - 1)] - 1))), "assigning variable x");
      } else {
        current_statement__ = 191;
        if (logical_lte(y_est[(1 - 1)], 0)) {
          current_statement__ = 190;
          assign(x, cons_list(index_uni(1), nil_index_list()), 1,
            "assigning variable x");
        } 
      }
    } else {
      current_statement__ = 189;
      if (logical_eq(data_ty_estpe, 2)) {
        current_statement__ = 187;
        if (logical_gt(y_est[(1 - 1)], 0)) {
          current_statement__ = 186;
          assign(x, cons_list(index_uni(1), nil_index_list()),
            (gamma_p(theta[(3 - 1)], (y_est[(1 - 1)] * theta[(1 - 1)])) -
              (stan::math::log((1 + q)) /
                (theta[(4 - 1)] * (theta[(2 - 1)] - 1)))),
            "assigning variable x");
        } else {
          current_statement__ = 185;
          if (logical_lte(y_est[(1 - 1)], 0)) {
            current_statement__ = 184;
            assign(x, cons_list(index_uni(1), nil_index_list()), 1,
              "assigning variable x");
          } 
        }
      } else {
        current_statement__ = 183;
        if (logical_eq(data_ty_estpe, 3)) {
          current_statement__ = 181;
          if (logical_gt(y_est[(1 - 1)], 0)) {
            current_statement__ = 180;
            assign(x, cons_list(index_uni(1), nil_index_list()),
              (gamma_p(theta[(3 - 1)], (y_est[(1 - 1)] * theta[(1 - 1)])) -
                (-q / (theta[(2 - 1)] - 1))), "assigning variable x");
          } else {
            current_statement__ = 179;
            if (logical_lte(y_est[(1 - 1)], 0)) {
              current_statement__ = 178;
              assign(x, cons_list(index_uni(1), nil_index_list()), 1,
                "assigning variable x");
            } 
          }
        } else {
          current_statement__ = 177;
          if (logical_eq(data_ty_estpe, 4)) {
            current_statement__ = 175;
            if (logical_gt(y_est[(1 - 1)], 0)) {
              current_statement__ = 174;
              assign(x, cons_list(index_uni(1), nil_index_list()),
                (gamma_p(theta[(3 - 1)], (y_est[(1 - 1)] * theta[(1 - 1)])) -
                  (stan::math::log((1 - q)) /
                    (theta[(4 - 1)] * (theta[(2 - 1)] - 1)))),
                "assigning variable x");
            } else {
              current_statement__ = 173;
              if (logical_lte(y_est[(1 - 1)], 0)) {
                current_statement__ = 172;
                assign(x, cons_list(index_uni(1), nil_index_list()), 1,
                  "assigning variable x");
              } 
            }
          } 
        }
      }
    }
    current_statement__ = 196;
    return x;
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
  }
  
}
struct algebra_system_functor__ {
template <typename T0__, typename T1__, typename T2__>
Eigen::Matrix<stan::promote_args_t<stan::value_type_t<T0__>, stan::value_type_t<T1__>,
T2__>, -1, 1>
operator()(const T0__& y_est, const T1__& theta,
           const std::vector<T2__>& x_r, const std::vector<int>& x_i,
           std::ostream* pstream__)  const 
{
return algebra_system(y_est, theta, x_r, x_i, pstream__);
}
};
template <bool propto__, typename T0__, typename T1__, typename T2__,
typename T3__, typename T4__>
stan::promote_args_t<T0__, T1__, T2__, T3__,
T4__>
pert_dist_lpdf(const T0__& theta, const T1__& alpha, const T2__& beta,
               const T3__& lb, const T4__& ub, std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<T0__,
          T1__,
          T2__,
          T3__,
          T4__>;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  (void) DUMMY_VAR__;  // suppress unused var warning
  
  try {
    local_scalar_t__ x1;
    x1 = DUMMY_VAR__;
    
    local_scalar_t__ x2;
    x2 = DUMMY_VAR__;
    
    local_scalar_t__ x3;
    x3 = DUMMY_VAR__;
    
    local_scalar_t__ x4;
    x4 = DUMMY_VAR__;
    
    current_statement__ = 202;
    x1 = ((alpha - 1) * stan::math::log((theta - lb)));
    current_statement__ = 203;
    x2 = ((beta - 1) * stan::math::log((ub - theta)));
    current_statement__ = 204;
    x3 = (((alpha + beta) - 1) * stan::math::log((ub - lb)));
    current_statement__ = 205;
    x4 = lbeta(alpha, beta);
    current_statement__ = 206;
    return (((x1 + x2) - x3) - x4);
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
  }
  
}
struct pert_dist_lpdf_functor__ {
template <bool propto__, typename T0__, typename T1__, typename T2__,
typename T3__, typename T4__>
stan::promote_args_t<T0__, T1__, T2__, T3__,
T4__>
operator()(const T0__& theta, const T1__& alpha, const T2__& beta,
           const T3__& lb, const T4__& ub, std::ostream* pstream__)  const 
{
return pert_dist_lpdf<propto__>(theta, alpha, beta, lb, ub, pstream__);
}
};
#include <stan_meta_header.hpp>
class model_mG4c final : public model_base_crtp<model_mG4c> {
private:
  int N;
  std::vector<int> n;
  int nc;
  int maxN;
  int maxNc;
  std::vector<std::vector<int>> nij;
  Eigen::Matrix<double, -1, -1> y;
  Eigen::Matrix<double, -1, 1> x;
  double q;
  double shift;
  double init_b;
  Eigen::Matrix<double, -1, 1> priormu;
  Eigen::Matrix<double, -1, 1> priorlb;
  Eigen::Matrix<double, -1, 1> priorub;
  Eigen::Matrix<double, -1, 1> shape1;
  Eigen::Matrix<double, -1, 1> shape2;
  Eigen::Matrix<double, -1, -1> priorSigma;
  double truncd;
  int data_type;
  int is_increasing;
  double L;
  int is_decreasing;
  double U;
  std::vector<double> x_r;
  std::vector<int> x_i;
 
public:
  ~model_mG4c() { }
  
  inline std::string model_name() const final { return "model_mG4c"; }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.26.1-4-gd72b68b7-dirty", "stancflags = "};
  }
  
  
  model_mG4c(stan::io::var_context& context__,
             unsigned int random_seed__ = 0,
             std::ostream* pstream__ = nullptr) : model_base_crtp(0) {
    using local_scalar_t__ = double ;
    boost::ecuyer1988 base_rng__ = 
        stan::services::util::create_rng(random_seed__, 0);
    (void) base_rng__;  // suppress unused var warning
    static const char* function__ = "model_mG4c_namespace::model_mG4c";
    (void) function__;  // suppress unused var warning
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    
    try {
      int pos__;
      pos__ = std::numeric_limits<int>::min();
      
      pos__ = 1;
      current_statement__ = 134;
      context__.validate_dims("data initialization","N","int",
          context__.to_vec());
      N = std::numeric_limits<int>::min();
      
      current_statement__ = 134;
      N = context__.vals_i("N")[(1 - 1)];
      current_statement__ = 135;
      validate_non_negative_index("n", "N", N);
      current_statement__ = 136;
      context__.validate_dims("data initialization","n","int",
          context__.to_vec(N));
      n = std::vector<int>(N, std::numeric_limits<int>::min());
      
      current_statement__ = 136;
      assign(n, nil_index_list(), context__.vals_i("n"),
        "assigning variable n");
      current_statement__ = 137;
      context__.validate_dims("data initialization","nc","int",
          context__.to_vec());
      nc = std::numeric_limits<int>::min();
      
      current_statement__ = 137;
      nc = context__.vals_i("nc")[(1 - 1)];
      current_statement__ = 138;
      context__.validate_dims("data initialization","maxN","int",
          context__.to_vec());
      maxN = std::numeric_limits<int>::min();
      
      current_statement__ = 138;
      maxN = context__.vals_i("maxN")[(1 - 1)];
      current_statement__ = 139;
      context__.validate_dims("data initialization","maxNc","int",
          context__.to_vec());
      maxNc = std::numeric_limits<int>::min();
      
      current_statement__ = 139;
      maxNc = context__.vals_i("maxNc")[(1 - 1)];
      current_statement__ = 140;
      validate_non_negative_index("nij", "N", N);
      current_statement__ = 141;
      validate_non_negative_index("nij", "maxNc", maxNc);
      current_statement__ = 142;
      context__.validate_dims("data initialization","nij","int",
          context__.to_vec(N, maxNc));
      nij = std::vector<std::vector<int>>(N, std::vector<int>(maxNc, std::numeric_limits<int>::min()));
      
      {
        std::vector<int> nij_flat__;
        current_statement__ = 142;
        assign(nij_flat__, nil_index_list(), context__.vals_i("nij"),
          "assigning variable nij_flat__");
        current_statement__ = 142;
        pos__ = 1;
        current_statement__ = 142;
        for (int sym1__ = 1; sym1__ <= maxNc; ++sym1__) {
          current_statement__ = 142;
          for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
            current_statement__ = 142;
            assign(nij,
              cons_list(index_uni(sym2__),
                cons_list(index_uni(sym1__), nil_index_list())),
              nij_flat__[(pos__ - 1)], "assigning variable nij");
            current_statement__ = 142;
            pos__ = (pos__ + 1);}}
      }
      current_statement__ = 143;
      validate_non_negative_index("y", "nc", nc);
      current_statement__ = 144;
      validate_non_negative_index("y", "maxN", maxN);
      current_statement__ = 145;
      context__.validate_dims("data initialization","y","double",
          context__.to_vec(nc, maxN));
      y = Eigen::Matrix<double, -1, -1>(nc, maxN);
      stan::math::fill(y, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> y_flat__;
        current_statement__ = 145;
        assign(y_flat__, nil_index_list(), context__.vals_r("y"),
          "assigning variable y_flat__");
        current_statement__ = 145;
        pos__ = 1;
        current_statement__ = 145;
        for (int sym1__ = 1; sym1__ <= maxN; ++sym1__) {
          current_statement__ = 145;
          for (int sym2__ = 1; sym2__ <= nc; ++sym2__) {
            current_statement__ = 145;
            assign(y,
              cons_list(index_uni(sym2__),
                cons_list(index_uni(sym1__), nil_index_list())),
              y_flat__[(pos__ - 1)], "assigning variable y");
            current_statement__ = 145;
            pos__ = (pos__ + 1);}}
      }
      current_statement__ = 146;
      validate_non_negative_index("x", "N", N);
      current_statement__ = 147;
      context__.validate_dims("data initialization","x","double",
          context__.to_vec(N));
      x = Eigen::Matrix<double, -1, 1>(N);
      stan::math::fill(x, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> x_flat__;
        current_statement__ = 147;
        assign(x_flat__, nil_index_list(), context__.vals_r("x"),
          "assigning variable x_flat__");
        current_statement__ = 147;
        pos__ = 1;
        current_statement__ = 147;
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          current_statement__ = 147;
          assign(x, cons_list(index_uni(sym1__), nil_index_list()),
            x_flat__[(pos__ - 1)], "assigning variable x");
          current_statement__ = 147;
          pos__ = (pos__ + 1);}
      }
      current_statement__ = 148;
      context__.validate_dims("data initialization","q","double",
          context__.to_vec());
      q = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 148;
      q = context__.vals_r("q")[(1 - 1)];
      current_statement__ = 149;
      context__.validate_dims("data initialization","shift","double",
          context__.to_vec());
      shift = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 149;
      shift = context__.vals_r("shift")[(1 - 1)];
      current_statement__ = 150;
      context__.validate_dims("data initialization","init_b","double",
          context__.to_vec());
      init_b = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 150;
      init_b = context__.vals_r("init_b")[(1 - 1)];
      current_statement__ = 151;
      context__.validate_dims("data initialization","priormu","double",
          context__.to_vec(6));
      priormu = Eigen::Matrix<double, -1, 1>(6);
      stan::math::fill(priormu, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> priormu_flat__;
        current_statement__ = 151;
        assign(priormu_flat__, nil_index_list(), context__.vals_r("priormu"),
          "assigning variable priormu_flat__");
        current_statement__ = 151;
        pos__ = 1;
        current_statement__ = 151;
        for (int sym1__ = 1; sym1__ <= 6; ++sym1__) {
          current_statement__ = 151;
          assign(priormu, cons_list(index_uni(sym1__), nil_index_list()),
            priormu_flat__[(pos__ - 1)], "assigning variable priormu");
          current_statement__ = 151;
          pos__ = (pos__ + 1);}
      }
      current_statement__ = 152;
      context__.validate_dims("data initialization","priorlb","double",
          context__.to_vec(6));
      priorlb = Eigen::Matrix<double, -1, 1>(6);
      stan::math::fill(priorlb, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> priorlb_flat__;
        current_statement__ = 152;
        assign(priorlb_flat__, nil_index_list(), context__.vals_r("priorlb"),
          "assigning variable priorlb_flat__");
        current_statement__ = 152;
        pos__ = 1;
        current_statement__ = 152;
        for (int sym1__ = 1; sym1__ <= 6; ++sym1__) {
          current_statement__ = 152;
          assign(priorlb, cons_list(index_uni(sym1__), nil_index_list()),
            priorlb_flat__[(pos__ - 1)], "assigning variable priorlb");
          current_statement__ = 152;
          pos__ = (pos__ + 1);}
      }
      current_statement__ = 153;
      context__.validate_dims("data initialization","priorub","double",
          context__.to_vec(6));
      priorub = Eigen::Matrix<double, -1, 1>(6);
      stan::math::fill(priorub, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> priorub_flat__;
        current_statement__ = 153;
        assign(priorub_flat__, nil_index_list(), context__.vals_r("priorub"),
          "assigning variable priorub_flat__");
        current_statement__ = 153;
        pos__ = 1;
        current_statement__ = 153;
        for (int sym1__ = 1; sym1__ <= 6; ++sym1__) {
          current_statement__ = 153;
          assign(priorub, cons_list(index_uni(sym1__), nil_index_list()),
            priorub_flat__[(pos__ - 1)], "assigning variable priorub");
          current_statement__ = 153;
          pos__ = (pos__ + 1);}
      }
      current_statement__ = 154;
      context__.validate_dims("data initialization","shape1","double",
          context__.to_vec(6));
      shape1 = Eigen::Matrix<double, -1, 1>(6);
      stan::math::fill(shape1, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> shape1_flat__;
        current_statement__ = 154;
        assign(shape1_flat__, nil_index_list(), context__.vals_r("shape1"),
          "assigning variable shape1_flat__");
        current_statement__ = 154;
        pos__ = 1;
        current_statement__ = 154;
        for (int sym1__ = 1; sym1__ <= 6; ++sym1__) {
          current_statement__ = 154;
          assign(shape1, cons_list(index_uni(sym1__), nil_index_list()),
            shape1_flat__[(pos__ - 1)], "assigning variable shape1");
          current_statement__ = 154;
          pos__ = (pos__ + 1);}
      }
      current_statement__ = 155;
      context__.validate_dims("data initialization","shape2","double",
          context__.to_vec(6));
      shape2 = Eigen::Matrix<double, -1, 1>(6);
      stan::math::fill(shape2, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> shape2_flat__;
        current_statement__ = 155;
        assign(shape2_flat__, nil_index_list(), context__.vals_r("shape2"),
          "assigning variable shape2_flat__");
        current_statement__ = 155;
        pos__ = 1;
        current_statement__ = 155;
        for (int sym1__ = 1; sym1__ <= 6; ++sym1__) {
          current_statement__ = 155;
          assign(shape2, cons_list(index_uni(sym1__), nil_index_list()),
            shape2_flat__[(pos__ - 1)], "assigning variable shape2");
          current_statement__ = 155;
          pos__ = (pos__ + 1);}
      }
      current_statement__ = 156;
      context__.validate_dims("data initialization","priorSigma","double",
          context__.to_vec(5, 5));
      priorSigma = Eigen::Matrix<double, -1, -1>(5, 5);
      stan::math::fill(priorSigma, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> priorSigma_flat__;
        current_statement__ = 156;
        assign(priorSigma_flat__, nil_index_list(),
          context__.vals_r("priorSigma"),
          "assigning variable priorSigma_flat__");
        current_statement__ = 156;
        pos__ = 1;
        current_statement__ = 156;
        for (int sym1__ = 1; sym1__ <= 5; ++sym1__) {
          current_statement__ = 156;
          for (int sym2__ = 1; sym2__ <= 5; ++sym2__) {
            current_statement__ = 156;
            assign(priorSigma,
              cons_list(index_uni(sym2__),
                cons_list(index_uni(sym1__), nil_index_list())),
              priorSigma_flat__[(pos__ - 1)], "assigning variable priorSigma");
            current_statement__ = 156;
            pos__ = (pos__ + 1);}}
      }
      current_statement__ = 156;
      current_statement__ = 156;
      check_cov_matrix(function__, "priorSigma", priorSigma);
      current_statement__ = 157;
      context__.validate_dims("data initialization","truncd","double",
          context__.to_vec());
      truncd = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 157;
      truncd = context__.vals_r("truncd")[(1 - 1)];
      current_statement__ = 158;
      context__.validate_dims("data initialization","data_type","int",
          context__.to_vec());
      data_type = std::numeric_limits<int>::min();
      
      current_statement__ = 158;
      data_type = context__.vals_i("data_type")[(1 - 1)];
      current_statement__ = 159;
      context__.validate_dims("data initialization","is_increasing","int",
          context__.to_vec());
      is_increasing = std::numeric_limits<int>::min();
      
      current_statement__ = 159;
      is_increasing = context__.vals_i("is_increasing")[(1 - 1)];
      current_statement__ = 159;
      current_statement__ = 159;
      check_greater_or_equal(function__, "is_increasing", is_increasing, 0);
      current_statement__ = 159;
      current_statement__ = 159;
      check_less_or_equal(function__, "is_increasing", is_increasing, 1);
      current_statement__ = 160;
      context__.validate_dims("data initialization","L","double",
          context__.to_vec());
      L = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 160;
      L = context__.vals_r("L")[(1 - 1)];
      current_statement__ = 161;
      context__.validate_dims("data initialization","is_decreasing","int",
          context__.to_vec());
      is_decreasing = std::numeric_limits<int>::min();
      
      current_statement__ = 161;
      is_decreasing = context__.vals_i("is_decreasing")[(1 - 1)];
      current_statement__ = 161;
      current_statement__ = 161;
      check_greater_or_equal(function__, "is_decreasing", is_decreasing, 0);
      current_statement__ = 161;
      current_statement__ = 161;
      check_less_or_equal(function__, "is_decreasing", is_decreasing, 1);
      current_statement__ = 162;
      context__.validate_dims("data initialization","U","double",
          context__.to_vec());
      U = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 162;
      U = context__.vals_r("U")[(1 - 1)];
      current_statement__ = 163;
      x_r = std::vector<double>(1, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 163;
      assign(x_r, nil_index_list(), std::vector<double>{q},
        "assigning variable x_r");
      current_statement__ = 164;
      x_i = std::vector<int>(1, std::numeric_limits<int>::min());
      
      current_statement__ = 164;
      assign(x_i, nil_index_list(), std::vector<int>{data_type},
        "assigning variable x_i");
      current_statement__ = 165;
      validate_non_negative_index("pars3i", "is_increasing", is_increasing);
      current_statement__ = 166;
      validate_non_negative_index("pars3d", "is_decreasing", is_decreasing);
      current_statement__ = 167;
      validate_non_negative_index("y_guess", "1", 1);
      current_statement__ = 168;
      validate_non_negative_index("y_est", "1", 1);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    num_params_r__ = 0U;
    
    try {
      num_params_r__ += 1;
      num_params_r__ += 1;
      num_params_r__ += is_increasing;
      num_params_r__ += is_decreasing;
      num_params_r__ += 1;
      num_params_r__ += 1;
      num_params_r__ += 1;
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI, stan::require_vector_like_t<VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR> log_prob_impl(VecR& params_r__,
                                                 VecI& params_i__,
                                                 std::ostream* pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    static const char* function__ = "model_mG4c_namespace::log_prob";
(void) function__;  // suppress unused var warning
    stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    
    try {
      local_scalar_t__ par1;
      par1 = DUMMY_VAR__;
      
      current_statement__ = 1;
      par1 = in__.scalar();
      current_statement__ = 1;
      if (jacobian__) {
        current_statement__ = 1;
        par1 = stan::math::lb_constrain(par1, 0, lp__);
      } else {
        current_statement__ = 1;
        par1 = stan::math::lb_constrain(par1, 0);
      }
      local_scalar_t__ par2;
      par2 = DUMMY_VAR__;
      
      current_statement__ = 2;
      par2 = in__.scalar();
      current_statement__ = 2;
      if (jacobian__) {
        current_statement__ = 2;
        par2 = stan::math::lub_constrain(par2, 0, 1, lp__);
      } else {
        current_statement__ = 2;
        par2 = stan::math::lub_constrain(par2, 0, 1);
      }
      std::vector<local_scalar_t__> pars3i;
      pars3i = std::vector<local_scalar_t__>(is_increasing, DUMMY_VAR__);
      
      current_statement__ = 3;
      for (int sym1__ = 1; sym1__ <= is_increasing; ++sym1__) {
        current_statement__ = 3;
        assign(pars3i, cons_list(index_uni(sym1__), nil_index_list()),
          in__.scalar(), "assigning variable pars3i");}
      current_statement__ = 3;
      for (int sym1__ = 1; sym1__ <= is_increasing; ++sym1__) {
        current_statement__ = 3;
        if (jacobian__) {
          current_statement__ = 3;
          assign(pars3i, cons_list(index_uni(sym1__), nil_index_list()),
            stan::math::lb_constrain(pars3i[(sym1__ - 1)], 0, lp__),
            "assigning variable pars3i");
        } else {
          current_statement__ = 3;
          assign(pars3i, cons_list(index_uni(sym1__), nil_index_list()),
            stan::math::lb_constrain(pars3i[(sym1__ - 1)], 0),
            "assigning variable pars3i");
        }}
      std::vector<local_scalar_t__> pars3d;
      pars3d = std::vector<local_scalar_t__>(is_decreasing, DUMMY_VAR__);
      
      current_statement__ = 4;
      for (int sym1__ = 1; sym1__ <= is_decreasing; ++sym1__) {
        current_statement__ = 4;
        assign(pars3d, cons_list(index_uni(sym1__), nil_index_list()),
          in__.scalar(), "assigning variable pars3d");}
      current_statement__ = 4;
      for (int sym1__ = 1; sym1__ <= is_decreasing; ++sym1__) {
        current_statement__ = 4;
        if (jacobian__) {
          current_statement__ = 4;
          assign(pars3d, cons_list(index_uni(sym1__), nil_index_list()),
            stan::math::lub_constrain(pars3d[(sym1__ - 1)], 0, 1, lp__),
            "assigning variable pars3d");
        } else {
          current_statement__ = 4;
          assign(pars3d, cons_list(index_uni(sym1__), nil_index_list()),
            stan::math::lub_constrain(pars3d[(sym1__ - 1)], 0, 1),
            "assigning variable pars3d");
        }}
      local_scalar_t__ par4;
      par4 = DUMMY_VAR__;
      
      current_statement__ = 5;
      par4 = in__.scalar();
      local_scalar_t__ par5;
      par5 = DUMMY_VAR__;
      
      current_statement__ = 6;
      par5 = in__.scalar();
      local_scalar_t__ par6;
      par6 = DUMMY_VAR__;
      
      current_statement__ = 7;
      par6 = in__.scalar();
      local_scalar_t__ b;
      b = DUMMY_VAR__;
      
      local_scalar_t__ a;
      a = DUMMY_VAR__;
      
      local_scalar_t__ c;
      c = DUMMY_VAR__;
      
      local_scalar_t__ par3;
      par3 = DUMMY_VAR__;
      
      local_scalar_t__ d;
      d = DUMMY_VAR__;
      
      local_scalar_t__ k;
      k = DUMMY_VAR__;
      
      local_scalar_t__ mu_inf;
      mu_inf = DUMMY_VAR__;
      
      local_scalar_t__ invsigma2;
      invsigma2 = DUMMY_VAR__;
      
      local_scalar_t__ mu_0;
      mu_0 = DUMMY_VAR__;
      
      Eigen::Matrix<local_scalar_t__, -1, 1> theta;
      theta = Eigen::Matrix<local_scalar_t__, -1, 1>(4);
      stan::math::fill(theta, DUMMY_VAR__);
      
      Eigen::Matrix<local_scalar_t__, -1, 1> y_guess;
      y_guess = Eigen::Matrix<local_scalar_t__, -1, 1>(1);
      stan::math::fill(y_guess, DUMMY_VAR__);
      
      Eigen::Matrix<local_scalar_t__, -1, 1> y_est;
      y_est = Eigen::Matrix<local_scalar_t__, -1, 1>(1);
      stan::math::fill(y_est, DUMMY_VAR__);
      
      local_scalar_t__ rho_cluster;
      rho_cluster = DUMMY_VAR__;
      
      current_statement__ = 21;
      rho_cluster = par6;
      current_statement__ = 22;
      mu_0 = par1;
      current_statement__ = 28;
      if ((primitive_value(logical_eq(data_type, 1)) || primitive_value(
          logical_eq(data_type, 3)))) {
        current_statement__ = 26;
        a = par1;
      } else {
        current_statement__ = 25;
        if ((primitive_value(logical_eq(data_type, 2)) || primitive_value(
            logical_eq(data_type, 4)))) {
          current_statement__ = 23;
          a = (stan::math::log(par1) - shift);
        } 
      }
      current_statement__ = 34;
      if (is_increasing) {
        current_statement__ = 32;
        par3 = (L + pars3i[(1 - 1)]);
      } else {
        current_statement__ = 31;
        if (is_decreasing) {
          current_statement__ = 29;
          par3 = (L + ((U - L) * pars3d[(1 - 1)]));
        } 
      }
      current_statement__ = 35;
      mu_inf = (par1 * par3);
      current_statement__ = 41;
      if ((primitive_value(logical_eq(data_type, 1)) || primitive_value(
          logical_eq(data_type, 3)))) {
        current_statement__ = 39;
        c = (mu_inf / mu_0);
      } else {
        current_statement__ = 38;
        if ((primitive_value(logical_eq(data_type, 2)) || primitive_value(
            logical_eq(data_type, 4)))) {
          current_statement__ = 36;
          c = ((stan::math::log(mu_inf) - shift) /
                (stan::math::log(mu_0) - shift));
        } 
      }
      current_statement__ = 42;
      d = stan::math::exp(par4);
      current_statement__ = 43;
      k = stan::math::log(par2);
      current_statement__ = 44;
      invsigma2 = stan::math::exp(par5);
      current_statement__ = 45;
      assign(theta, cons_list(index_uni(1), nil_index_list()),
        stan::math::exp(k), "assigning variable theta");
      current_statement__ = 46;
      assign(theta, cons_list(index_uni(2), nil_index_list()), c,
        "assigning variable theta");
      current_statement__ = 47;
      assign(theta, cons_list(index_uni(3), nil_index_list()), d,
        "assigning variable theta");
      current_statement__ = 48;
      assign(theta, cons_list(index_uni(4), nil_index_list()), a,
        "assigning variable theta");
      current_statement__ = 49;
      assign(y_guess, cons_list(index_uni(1), nil_index_list()), init_b,
        "assigning variable y_guess");
      current_statement__ = 50;
      assign(y_est, nil_index_list(),
        algebra_solver(algebra_system_functor__(), y_guess, theta, x_r, x_i,
          pstream__, 1e-10, stan::math::positive_infinity(), 1e3),
        "assigning variable y_est");
      current_statement__ = 51;
      b = y_est[(1 - 1)];
      {
        current_statement__ = 52;
        lp_accum__.add(
          pert_dist_lpdf<propto__>(par1, shape1[(1 - 1)], shape2[(1 - 1)],
            priorlb[(1 - 1)], priorub[(1 - 1)], pstream__));
        current_statement__ = 53;
        lp_accum__.add(
          pert_dist_lpdf<propto__>(par2, shape1[(2 - 1)], shape2[(2 - 1)],
            priorlb[(2 - 1)], priorub[(2 - 1)], pstream__));
        current_statement__ = 54;
        lp_accum__.add(
          pert_dist_lpdf<propto__>(par3, shape1[(3 - 1)], shape2[(3 - 1)],
            priorlb[(3 - 1)], priorub[(3 - 1)], pstream__));
        current_statement__ = 55;
        if (logical_gt(par4, truncd)) {
          current_statement__ = 55;
          lp_accum__.add(stan::math::negative_infinity());
        } else {
          current_statement__ = 55;
          lp_accum__.add(
            -normal_cdf_log(truncd, priormu[(4 - 1)],
               rvalue(priorSigma,
                 cons_list(index_uni(4),
                   cons_list(index_uni(4), nil_index_list())), "priorSigma")));
        }
        current_statement__ = 56;
        lp_accum__.add(
          normal_lpdf<propto__>(par4, priormu[(4 - 1)],
            rvalue(priorSigma,
              cons_list(index_uni(4),
                cons_list(index_uni(4), nil_index_list())), "priorSigma")));
        current_statement__ = 57;
        lp_accum__.add(
          normal_lpdf<propto__>(par5, priormu[(5 - 1)],
            rvalue(priorSigma,
              cons_list(index_uni(5),
                cons_list(index_uni(5), nil_index_list())), "priorSigma")));
        current_statement__ = 58;
        lp_accum__.add(
          pert_dist_lpdf<propto__>(par6, shape1[(6 - 1)], shape2[(6 - 1)],
            priorlb[(6 - 1)], priorub[(6 - 1)], pstream__));
        current_statement__ = 133;
        if ((primitive_value(logical_eq(data_type, 1)) || primitive_value(
            logical_eq(data_type, 3)))) {
          int cnt;
          cnt = std::numeric_limits<int>::min();
          
          current_statement__ = 98;
          cnt = 1;
          current_statement__ = 131;
          for (int i = 1; i <= N; ++i) {
            int nl;
            nl = std::numeric_limits<int>::min();
            
            local_scalar_t__ mx;
            mx = DUMMY_VAR__;
            
            current_statement__ = 101;
            mx = (a + ((a * (c - 1)) * gamma_cdf(x[(i - 1)], d, b)));
            current_statement__ = 102;
            nl = n[(i - 1)];
            current_statement__ = 129;
            for (int j = 1; j <= nl; ++j) {
              int lt;
              lt = std::numeric_limits<int>::min();
              
              current_statement__ = 103;
              lt = nij[(i - 1)][(j - 1)];
              current_statement__ = 104;
              validate_non_negative_index("resp", "lt", lt);
              Eigen::Matrix<local_scalar_t__, 1, -1> resp;
              resp = Eigen::Matrix<local_scalar_t__, 1, -1>(lt);
              stan::math::fill(resp, DUMMY_VAR__);
              
              current_statement__ = 106;
              validate_non_negative_index("m", "lt", lt);
              Eigen::Matrix<local_scalar_t__, 1, -1> m;
              m = Eigen::Matrix<local_scalar_t__, 1, -1>(lt);
              stan::math::fill(m, DUMMY_VAR__);
              
              current_statement__ = 108;
              validate_non_negative_index("P", "lt", lt);
              current_statement__ = 109;
              validate_non_negative_index("P", "lt", lt);
              Eigen::Matrix<local_scalar_t__, -1, -1> P;
              P = Eigen::Matrix<local_scalar_t__, -1, -1>(lt, lt);
              stan::math::fill(P, DUMMY_VAR__);
              
              current_statement__ = 111;
              validate_non_negative_index("Sigma", "lt", lt);
              current_statement__ = 112;
              validate_non_negative_index("Sigma", "lt", lt);
              Eigen::Matrix<local_scalar_t__, -1, -1> Sigma;
              Sigma = Eigen::Matrix<local_scalar_t__, -1, -1>(lt, lt);
              stan::math::fill(Sigma, DUMMY_VAR__);
              
              current_statement__ = 114;
              assign(resp, nil_index_list(),
                rvalue(y,
                  cons_list(index_uni(cnt),
                    cons_list(index_min_max(1, lt), nil_index_list())), "y"),
                "assigning variable resp");
              current_statement__ = 115;
              assign(m, nil_index_list(), rep_row_vector(mx, lt),
                "assigning variable m");
              current_statement__ = 124;
              for (int id1 = 1; id1 <= lt; ++id1) {
                current_statement__ = 122;
                for (int id2 = 1; id2 <= lt; ++id2) {
                  current_statement__ = 120;
                  if (logical_eq(id1, id2)) {
                    current_statement__ = 118;
                    assign(P,
                      cons_list(index_uni(id1),
                        cons_list(index_uni(id2), nil_index_list())), 1,
                      "assigning variable P");
                  } else {
                    current_statement__ = 116;
                    assign(P,
                      cons_list(index_uni(id1),
                        cons_list(index_uni(id2), nil_index_list())),
                      rho_cluster, "assigning variable P");
                  }}}
              current_statement__ = 125;
              assign(Sigma, nil_index_list(), multiply((1 / invsigma2), P),
                "assigning variable Sigma");
              current_statement__ = 126;
              lp_accum__.add(multi_normal_lpdf<false>(resp, m, Sigma));
              current_statement__ = 127;
              cnt = (cnt + 1);}}
        } else {
          current_statement__ = 96;
          if ((primitive_value(logical_eq(data_type, 2)) || primitive_value(
              logical_eq(data_type, 4)))) {
            int cnt;
            cnt = std::numeric_limits<int>::min();
            
            current_statement__ = 60;
            cnt = 1;
            current_statement__ = 94;
            for (int i = 1; i <= N; ++i) {
              int nl;
              nl = std::numeric_limits<int>::min();
              
              local_scalar_t__ mx;
              mx = DUMMY_VAR__;
              
              current_statement__ = 63;
              mx = (a + ((a * (c - 1)) * gamma_cdf(x[(i - 1)], d, b)));
              current_statement__ = 64;
              nl = n[(i - 1)];
              current_statement__ = 92;
              for (int j = 1; j <= nl; ++j) {
                int lt;
                lt = std::numeric_limits<int>::min();
                
                current_statement__ = 65;
                lt = nij[(i - 1)][(j - 1)];
                current_statement__ = 66;
                validate_non_negative_index("resp", "lt", lt);
                Eigen::Matrix<local_scalar_t__, 1, -1> resp;
                resp = Eigen::Matrix<local_scalar_t__, 1, -1>(lt);
                stan::math::fill(resp, DUMMY_VAR__);
                
                current_statement__ = 68;
                validate_non_negative_index("m", "lt", lt);
                Eigen::Matrix<local_scalar_t__, 1, -1> m;
                m = Eigen::Matrix<local_scalar_t__, 1, -1>(lt);
                stan::math::fill(m, DUMMY_VAR__);
                
                current_statement__ = 70;
                validate_non_negative_index("P", "lt", lt);
                current_statement__ = 71;
                validate_non_negative_index("P", "lt", lt);
                Eigen::Matrix<local_scalar_t__, -1, -1> P;
                P = Eigen::Matrix<local_scalar_t__, -1, -1>(lt, lt);
                stan::math::fill(P, DUMMY_VAR__);
                
                current_statement__ = 73;
                validate_non_negative_index("Sigma", "lt", lt);
                current_statement__ = 74;
                validate_non_negative_index("Sigma", "lt", lt);
                Eigen::Matrix<local_scalar_t__, -1, -1> Sigma;
                Sigma = Eigen::Matrix<local_scalar_t__, -1, -1>(lt, lt);
                stan::math::fill(Sigma, DUMMY_VAR__);
                
                current_statement__ = 76;
                assign(resp, nil_index_list(),
                  rvalue(y,
                    cons_list(index_uni(cnt),
                      cons_list(index_min_max(1, lt), nil_index_list())),
                    "y"), "assigning variable resp");
                current_statement__ = 77;
                assign(m, nil_index_list(), rep_row_vector(mx, lt),
                  "assigning variable m");
                current_statement__ = 86;
                for (int id1 = 1; id1 <= lt; ++id1) {
                  current_statement__ = 84;
                  for (int id2 = 1; id2 <= lt; ++id2) {
                    current_statement__ = 82;
                    if (logical_eq(id1, id2)) {
                      current_statement__ = 80;
                      assign(P,
                        cons_list(index_uni(id1),
                          cons_list(index_uni(id2), nil_index_list())), 1,
                        "assigning variable P");
                    } else {
                      current_statement__ = 78;
                      assign(P,
                        cons_list(index_uni(id1),
                          cons_list(index_uni(id2), nil_index_list())),
                        rho_cluster, "assigning variable P");
                    }}}
                current_statement__ = 87;
                assign(Sigma, nil_index_list(), multiply((1 / invsigma2), P),
                  "assigning variable Sigma");
                current_statement__ = 88;
                lp_accum__.add(multi_normal_lpdf<false>(resp, m, Sigma));
                current_statement__ = 89;
                lp_accum__.add(-sum(resp));
                current_statement__ = 90;
                cnt = (cnt + 1);}}
          } 
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
    } // log_prob_impl() 
    
  template <typename RNG, typename VecR, typename VecI, typename VecVar, stan::require_vector_like_vt<std::is_floating_point, VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr, stan::require_std_vector_vt<std::is_floating_point, VecVar>* = nullptr>
  inline void write_array_impl(RNG& base_rng__, VecR& params_r__,
                               VecI& params_i__, VecVar& vars__,
                               const bool emit_transformed_parameters__ = true,
                               const bool emit_generated_quantities__ = true,
                               std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    vars__.resize(0);
    stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
    static const char* function__ = "model_mG4c_namespace::write_array";
(void) function__;  // suppress unused var warning
    (void) function__;  // suppress unused var warning
    double lp__ = 0.0;
    (void) lp__;  // dummy to suppress unused var warning
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    
    try {
      double par1;
      par1 = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 1;
      par1 = in__.scalar();
      current_statement__ = 1;
      par1 = stan::math::lb_constrain(par1, 0);
      double par2;
      par2 = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 2;
      par2 = in__.scalar();
      current_statement__ = 2;
      par2 = stan::math::lub_constrain(par2, 0, 1);
      std::vector<double> pars3i;
      pars3i = std::vector<double>(is_increasing, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 3;
      for (int sym1__ = 1; sym1__ <= is_increasing; ++sym1__) {
        current_statement__ = 3;
        assign(pars3i, cons_list(index_uni(sym1__), nil_index_list()),
          in__.scalar(), "assigning variable pars3i");}
      current_statement__ = 3;
      for (int sym1__ = 1; sym1__ <= is_increasing; ++sym1__) {
        current_statement__ = 3;
        assign(pars3i, cons_list(index_uni(sym1__), nil_index_list()),
          stan::math::lb_constrain(pars3i[(sym1__ - 1)], 0),
          "assigning variable pars3i");}
      std::vector<double> pars3d;
      pars3d = std::vector<double>(is_decreasing, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 4;
      for (int sym1__ = 1; sym1__ <= is_decreasing; ++sym1__) {
        current_statement__ = 4;
        assign(pars3d, cons_list(index_uni(sym1__), nil_index_list()),
          in__.scalar(), "assigning variable pars3d");}
      current_statement__ = 4;
      for (int sym1__ = 1; sym1__ <= is_decreasing; ++sym1__) {
        current_statement__ = 4;
        assign(pars3d, cons_list(index_uni(sym1__), nil_index_list()),
          stan::math::lub_constrain(pars3d[(sym1__ - 1)], 0, 1),
          "assigning variable pars3d");}
      double par4;
      par4 = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 5;
      par4 = in__.scalar();
      double par5;
      par5 = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 6;
      par5 = in__.scalar();
      double par6;
      par6 = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 7;
      par6 = in__.scalar();
      double b;
      b = std::numeric_limits<double>::quiet_NaN();
      
      double a;
      a = std::numeric_limits<double>::quiet_NaN();
      
      double c;
      c = std::numeric_limits<double>::quiet_NaN();
      
      double par3;
      par3 = std::numeric_limits<double>::quiet_NaN();
      
      double d;
      d = std::numeric_limits<double>::quiet_NaN();
      
      double k;
      k = std::numeric_limits<double>::quiet_NaN();
      
      double mu_inf;
      mu_inf = std::numeric_limits<double>::quiet_NaN();
      
      double invsigma2;
      invsigma2 = std::numeric_limits<double>::quiet_NaN();
      
      double mu_0;
      mu_0 = std::numeric_limits<double>::quiet_NaN();
      
      Eigen::Matrix<double, -1, 1> theta;
      theta = Eigen::Matrix<double, -1, 1>(4);
      stan::math::fill(theta, std::numeric_limits<double>::quiet_NaN());
      
      Eigen::Matrix<double, -1, 1> y_guess;
      y_guess = Eigen::Matrix<double, -1, 1>(1);
      stan::math::fill(y_guess, std::numeric_limits<double>::quiet_NaN());
      
      Eigen::Matrix<double, -1, 1> y_est;
      y_est = Eigen::Matrix<double, -1, 1>(1);
      stan::math::fill(y_est, std::numeric_limits<double>::quiet_NaN());
      
      double rho_cluster;
      rho_cluster = std::numeric_limits<double>::quiet_NaN();
      
      vars__.emplace_back(par1);
      vars__.emplace_back(par2);
      for (int sym1__ = 1; sym1__ <= is_increasing; ++sym1__) {
        vars__.emplace_back(pars3i[(sym1__ - 1)]);}
      for (int sym1__ = 1; sym1__ <= is_decreasing; ++sym1__) {
        vars__.emplace_back(pars3d[(sym1__ - 1)]);}
      vars__.emplace_back(par4);
      vars__.emplace_back(par5);
      vars__.emplace_back(par6);
      if (logical_negation((primitive_value(emit_transformed_parameters__) ||
            primitive_value(emit_generated_quantities__)))) {
        return ;
      } 
      current_statement__ = 21;
      rho_cluster = par6;
      current_statement__ = 22;
      mu_0 = par1;
      current_statement__ = 28;
      if ((primitive_value(logical_eq(data_type, 1)) || primitive_value(
          logical_eq(data_type, 3)))) {
        current_statement__ = 26;
        a = par1;
      } else {
        current_statement__ = 25;
        if ((primitive_value(logical_eq(data_type, 2)) || primitive_value(
            logical_eq(data_type, 4)))) {
          current_statement__ = 23;
          a = (stan::math::log(par1) - shift);
        } 
      }
      current_statement__ = 34;
      if (is_increasing) {
        current_statement__ = 32;
        par3 = (L + pars3i[(1 - 1)]);
      } else {
        current_statement__ = 31;
        if (is_decreasing) {
          current_statement__ = 29;
          par3 = (L + ((U - L) * pars3d[(1 - 1)]));
        } 
      }
      current_statement__ = 35;
      mu_inf = (par1 * par3);
      current_statement__ = 41;
      if ((primitive_value(logical_eq(data_type, 1)) || primitive_value(
          logical_eq(data_type, 3)))) {
        current_statement__ = 39;
        c = (mu_inf / mu_0);
      } else {
        current_statement__ = 38;
        if ((primitive_value(logical_eq(data_type, 2)) || primitive_value(
            logical_eq(data_type, 4)))) {
          current_statement__ = 36;
          c = ((stan::math::log(mu_inf) - shift) /
                (stan::math::log(mu_0) - shift));
        } 
      }
      current_statement__ = 42;
      d = stan::math::exp(par4);
      current_statement__ = 43;
      k = stan::math::log(par2);
      current_statement__ = 44;
      invsigma2 = stan::math::exp(par5);
      current_statement__ = 45;
      assign(theta, cons_list(index_uni(1), nil_index_list()),
        stan::math::exp(k), "assigning variable theta");
      current_statement__ = 46;
      assign(theta, cons_list(index_uni(2), nil_index_list()), c,
        "assigning variable theta");
      current_statement__ = 47;
      assign(theta, cons_list(index_uni(3), nil_index_list()), d,
        "assigning variable theta");
      current_statement__ = 48;
      assign(theta, cons_list(index_uni(4), nil_index_list()), a,
        "assigning variable theta");
      current_statement__ = 49;
      assign(y_guess, cons_list(index_uni(1), nil_index_list()), init_b,
        "assigning variable y_guess");
      current_statement__ = 50;
      assign(y_est, nil_index_list(),
        algebra_solver(algebra_system_functor__(), y_guess, theta, x_r, x_i,
          pstream__, 1e-10, stan::math::positive_infinity(), 1e3),
        "assigning variable y_est");
      current_statement__ = 51;
      b = y_est[(1 - 1)];
      if (emit_transformed_parameters__) {
        vars__.emplace_back(b);
        vars__.emplace_back(a);
        vars__.emplace_back(c);
        vars__.emplace_back(par3);
        vars__.emplace_back(d);
        vars__.emplace_back(k);
        vars__.emplace_back(mu_inf);
        vars__.emplace_back(invsigma2);
        vars__.emplace_back(mu_0);
        for (int sym1__ = 1; sym1__ <= 4; ++sym1__) {
          vars__.emplace_back(theta[(sym1__ - 1)]);}
        for (int sym1__ = 1; sym1__ <= 1; ++sym1__) {
          vars__.emplace_back(y_guess[(sym1__ - 1)]);}
        for (int sym1__ = 1; sym1__ <= 1; ++sym1__) {
          vars__.emplace_back(y_est[(sym1__ - 1)]);}
        vars__.emplace_back(rho_cluster);
      } 
      if (logical_negation(emit_generated_quantities__)) {
        return ;
      } 
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    } // write_array_impl() 
    
  template <typename VecVar, typename VecI, stan::require_std_vector_t<VecVar>* = nullptr, stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void transform_inits_impl(const stan::io::var_context& context__,
                                   VecI& params_i__, VecVar& vars__,
                                   std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    vars__.clear();
    vars__.reserve(num_params_r__);
    
    try {
      int pos__;
      pos__ = std::numeric_limits<int>::min();
      
      pos__ = 1;
      double par1;
      par1 = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 1;
      par1 = context__.vals_r("par1")[(1 - 1)];
      double par1_free__;
      par1_free__ = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 1;
      par1_free__ = stan::math::lb_free(par1, 0);
      double par2;
      par2 = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 2;
      par2 = context__.vals_r("par2")[(1 - 1)];
      double par2_free__;
      par2_free__ = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 2;
      par2_free__ = stan::math::lub_free(par2, 0, 1);
      std::vector<double> pars3i;
      pars3i = std::vector<double>(is_increasing, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 3;
      assign(pars3i, nil_index_list(), context__.vals_r("pars3i"),
        "assigning variable pars3i");
      std::vector<double> pars3i_free__;
      pars3i_free__ = std::vector<double>(is_increasing, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 3;
      for (int sym1__ = 1; sym1__ <= is_increasing; ++sym1__) {
        current_statement__ = 3;
        assign(pars3i_free__, cons_list(index_uni(sym1__), nil_index_list()),
          stan::math::lb_free(pars3i[(sym1__ - 1)], 0),
          "assigning variable pars3i_free__");}
      std::vector<double> pars3d;
      pars3d = std::vector<double>(is_decreasing, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 4;
      assign(pars3d, nil_index_list(), context__.vals_r("pars3d"),
        "assigning variable pars3d");
      std::vector<double> pars3d_free__;
      pars3d_free__ = std::vector<double>(is_decreasing, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 4;
      for (int sym1__ = 1; sym1__ <= is_decreasing; ++sym1__) {
        current_statement__ = 4;
        assign(pars3d_free__, cons_list(index_uni(sym1__), nil_index_list()),
          stan::math::lub_free(pars3d[(sym1__ - 1)], 0, 1),
          "assigning variable pars3d_free__");}
      double par4;
      par4 = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 5;
      par4 = context__.vals_r("par4")[(1 - 1)];
      double par5;
      par5 = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 6;
      par5 = context__.vals_r("par5")[(1 - 1)];
      double par6;
      par6 = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 7;
      par6 = context__.vals_r("par6")[(1 - 1)];
      vars__.emplace_back(par1_free__);
      vars__.emplace_back(par2_free__);
      for (int sym1__ = 1; sym1__ <= is_increasing; ++sym1__) {
        vars__.emplace_back(pars3i_free__[(sym1__ - 1)]);}
      for (int sym1__ = 1; sym1__ <= is_decreasing; ++sym1__) {
        vars__.emplace_back(pars3d_free__[(sym1__ - 1)]);}
      vars__.emplace_back(par4);
      vars__.emplace_back(par5);
      vars__.emplace_back(par6);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    } // transform_inits_impl() 
    
  inline void get_param_names(std::vector<std::string>& names__) const {
    
    names__.clear();
    names__.emplace_back("par1");
    names__.emplace_back("par2");
    names__.emplace_back("pars3i");
    names__.emplace_back("pars3d");
    names__.emplace_back("par4");
    names__.emplace_back("par5");
    names__.emplace_back("par6");
    names__.emplace_back("b");
    names__.emplace_back("a");
    names__.emplace_back("c");
    names__.emplace_back("par3");
    names__.emplace_back("d");
    names__.emplace_back("k");
    names__.emplace_back("mu_inf");
    names__.emplace_back("invsigma2");
    names__.emplace_back("mu_0");
    names__.emplace_back("theta");
    names__.emplace_back("y_guess");
    names__.emplace_back("y_est");
    names__.emplace_back("rho_cluster");
    } // get_param_names() 
    
  inline void get_dims(std::vector<std::vector<size_t>>& dimss__) const {
    dimss__.clear();
    dimss__.emplace_back(std::vector<size_t>{});
    
    dimss__.emplace_back(std::vector<size_t>{});
    
    dimss__.emplace_back(std::vector<size_t>{
                                             static_cast<size_t>(is_increasing)
                                             });
    
    dimss__.emplace_back(std::vector<size_t>{
                                             static_cast<size_t>(is_decreasing)
                                             });
    
    dimss__.emplace_back(std::vector<size_t>{});
    
    dimss__.emplace_back(std::vector<size_t>{});
    
    dimss__.emplace_back(std::vector<size_t>{});
    
    dimss__.emplace_back(std::vector<size_t>{});
    
    dimss__.emplace_back(std::vector<size_t>{});
    
    dimss__.emplace_back(std::vector<size_t>{});
    
    dimss__.emplace_back(std::vector<size_t>{});
    
    dimss__.emplace_back(std::vector<size_t>{});
    
    dimss__.emplace_back(std::vector<size_t>{});
    
    dimss__.emplace_back(std::vector<size_t>{});
    
    dimss__.emplace_back(std::vector<size_t>{});
    
    dimss__.emplace_back(std::vector<size_t>{});
    
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(4)});
    
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(1)});
    
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(1)});
    
    dimss__.emplace_back(std::vector<size_t>{});
    
    } // get_dims() 
    
  inline void constrained_param_names(
                                      std::vector<std::string>& param_names__,
                                      bool emit_transformed_parameters__ = true,
                                      bool emit_generated_quantities__ = true) const
    final {
    
    param_names__.emplace_back(std::string() + "par1");
    param_names__.emplace_back(std::string() + "par2");
    for (int sym1__ = 1; sym1__ <= is_increasing; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "pars3i" + '.' + std::to_string(sym1__));
      }}
    for (int sym1__ = 1; sym1__ <= is_decreasing; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "pars3d" + '.' + std::to_string(sym1__));
      }}
    param_names__.emplace_back(std::string() + "par4");
    param_names__.emplace_back(std::string() + "par5");
    param_names__.emplace_back(std::string() + "par6");
    if (emit_transformed_parameters__) {
      param_names__.emplace_back(std::string() + "b");
      param_names__.emplace_back(std::string() + "a");
      param_names__.emplace_back(std::string() + "c");
      param_names__.emplace_back(std::string() + "par3");
      param_names__.emplace_back(std::string() + "d");
      param_names__.emplace_back(std::string() + "k");
      param_names__.emplace_back(std::string() + "mu_inf");
      param_names__.emplace_back(std::string() + "invsigma2");
      param_names__.emplace_back(std::string() + "mu_0");
      for (int sym1__ = 1; sym1__ <= 4; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "theta" + '.' + std::to_string(sym1__));
        }}
      for (int sym1__ = 1; sym1__ <= 1; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "y_guess" + '.' + std::to_string(sym1__));
        }}
      for (int sym1__ = 1; sym1__ <= 1; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "y_est" + '.' + std::to_string(sym1__));
        }}
      param_names__.emplace_back(std::string() + "rho_cluster");
    }
    
    if (emit_generated_quantities__) {
      
    }
    
    } // constrained_param_names() 
    
  inline void unconstrained_param_names(
                                        std::vector<std::string>& param_names__,
                                        bool emit_transformed_parameters__ = true,
                                        bool emit_generated_quantities__ = true) const
    final {
    
    param_names__.emplace_back(std::string() + "par1");
    param_names__.emplace_back(std::string() + "par2");
    for (int sym1__ = 1; sym1__ <= is_increasing; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "pars3i" + '.' + std::to_string(sym1__));
      }}
    for (int sym1__ = 1; sym1__ <= is_decreasing; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "pars3d" + '.' + std::to_string(sym1__));
      }}
    param_names__.emplace_back(std::string() + "par4");
    param_names__.emplace_back(std::string() + "par5");
    param_names__.emplace_back(std::string() + "par6");
    if (emit_transformed_parameters__) {
      param_names__.emplace_back(std::string() + "b");
      param_names__.emplace_back(std::string() + "a");
      param_names__.emplace_back(std::string() + "c");
      param_names__.emplace_back(std::string() + "par3");
      param_names__.emplace_back(std::string() + "d");
      param_names__.emplace_back(std::string() + "k");
      param_names__.emplace_back(std::string() + "mu_inf");
      param_names__.emplace_back(std::string() + "invsigma2");
      param_names__.emplace_back(std::string() + "mu_0");
      for (int sym1__ = 1; sym1__ <= 4; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "theta" + '.' + std::to_string(sym1__));
        }}
      for (int sym1__ = 1; sym1__ <= 1; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "y_guess" + '.' + std::to_string(sym1__));
        }}
      for (int sym1__ = 1; sym1__ <= 1; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "y_est" + '.' + std::to_string(sym1__));
        }}
      param_names__.emplace_back(std::string() + "rho_cluster");
    }
    
    if (emit_generated_quantities__) {
      
    }
    
    } // unconstrained_param_names() 
    
  inline std::string get_constrained_sizedtypes() const {
    stringstream s__;
    s__ << "[{\"name\":\"par1\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"par2\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"pars3i\",\"type\":{\"name\":\"array\",\"length\":" << is_increasing << ",\"element_type\":{\"name\":\"real\"}},\"block\":\"parameters\"},{\"name\":\"pars3d\",\"type\":{\"name\":\"array\",\"length\":" << is_decreasing << ",\"element_type\":{\"name\":\"real\"}},\"block\":\"parameters\"},{\"name\":\"par4\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"par5\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"par6\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"b\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"a\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"c\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"par3\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"d\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"k\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"mu_inf\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"invsigma2\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"mu_0\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"theta\",\"type\":{\"name\":\"vector\",\"length\":" << 4 << "},\"block\":\"transformed_parameters\"},{\"name\":\"y_guess\",\"type\":{\"name\":\"vector\",\"length\":" << 1 << "},\"block\":\"transformed_parameters\"},{\"name\":\"y_est\",\"type\":{\"name\":\"vector\",\"length\":" << 1 << "},\"block\":\"transformed_parameters\"},{\"name\":\"rho_cluster\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"}]";
    return s__.str();
    } // get_constrained_sizedtypes() 
    
  inline std::string get_unconstrained_sizedtypes() const {
    stringstream s__;
    s__ << "[{\"name\":\"par1\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"par2\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"pars3i\",\"type\":{\"name\":\"array\",\"length\":" << is_increasing << ",\"element_type\":{\"name\":\"real\"}},\"block\":\"parameters\"},{\"name\":\"pars3d\",\"type\":{\"name\":\"array\",\"length\":" << is_decreasing << ",\"element_type\":{\"name\":\"real\"}},\"block\":\"parameters\"},{\"name\":\"par4\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"par5\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"par6\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"b\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"a\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"c\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"par3\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"d\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"k\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"mu_inf\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"invsigma2\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"mu_0\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"theta\",\"type\":{\"name\":\"vector\",\"length\":" << 4 << "},\"block\":\"transformed_parameters\"},{\"name\":\"y_guess\",\"type\":{\"name\":\"vector\",\"length\":" << 1 << "},\"block\":\"transformed_parameters\"},{\"name\":\"y_est\",\"type\":{\"name\":\"vector\",\"length\":" << 1 << "},\"block\":\"transformed_parameters\"},{\"name\":\"rho_cluster\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"}]";
    return s__.str();
    } // get_unconstrained_sizedtypes() 
    
  
    // Begin method overload boilerplate
    template <typename RNG>
    inline void write_array(RNG& base_rng,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                            const bool emit_transformed_parameters = true,
                            const bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      std::vector<double> vars_vec(vars.size());
      std::vector<int> params_i;
      write_array_impl(base_rng, params_r, params_i, vars_vec,
          emit_transformed_parameters, emit_generated_quantities, pstream);
      vars.resize(vars_vec.size());
      for (int i = 0; i < vars.size(); ++i) {
        vars.coeffRef(i) = vars_vec[i];
      }
    }
    template <typename RNG>
    inline void write_array(RNG& base_rng, std::vector<double>& params_r,
                            std::vector<int>& params_i,
                            std::vector<double>& vars,
                            bool emit_transformed_parameters = true,
                            bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      write_array_impl(base_rng, params_r, params_i, vars, emit_transformed_parameters, emit_generated_quantities, pstream);
    }
    template <bool propto__, bool jacobian__, typename T_>
    inline T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
                       std::ostream* pstream = nullptr) const {
      Eigen::Matrix<int, -1, 1> params_i;
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }
    template <bool propto__, bool jacobian__, typename T__>
    inline T__ log_prob(std::vector<T__>& params_r,
                        std::vector<int>& params_i,
                        std::ostream* pstream = nullptr) const {
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }
  
    inline void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream = nullptr) const final {
      std::vector<double> params_r_vec(params_r.size());
      std::vector<int> params_i;
      transform_inits_impl(context, params_i, params_r_vec, pstream);
      params_r.resize(params_r_vec.size());
      for (int i = 0; i < params_r.size(); ++i) {
        params_r.coeffRef(i) = params_r_vec[i];
      }
    }
    inline void transform_inits(const stan::io::var_context& context,
                                std::vector<int>& params_i,
                                std::vector<double>& vars,
                                std::ostream* pstream = nullptr) const final {
      transform_inits_impl(context, params_i, vars, pstream);
    }        
};
}
using stan_model = model_mG4c_namespace::model_mG4c;
#ifndef USING_R
// Boilerplate
stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return model_mG4c_namespace::profiles__;
}
#endif
#endif
