# Generated by rstantools.  Do not edit by hand.

# names of stan models
stanmodels <- c("mE4_Q_COv", "mE4_Q", "mE4", "mE4c", "mE4COV", "mG4_Q_COV", "mG4_Q", "mG4", "mG4c", "mG4COV", "mH0_Q", "mH0", "mH0c", "mH4_Q_COV", "mH4_Q", "mH4", "mH4c", "mH4COV", "mIE4_Q_COV", "mIE4_Q", "mIE4", "mIE4c", "mIE4COV", "mL4_Q_COV", "mL4_Q", "mL4", "mL4c", "mL4COV", "mLN4_Q_COV", "mLN4_Q", "mLN4", "mLN4c", "mLN4COV", "mP4_Q_COV", "mP4_Q", "mP4", "mP4c", "mP4COV", "mQE4_Q_COV", "mQE4_Q", "mQE4", "mQE4c", "mQE4COV", "mSM_Q", "mSM", "mSMc")

# load each stan module
Rcpp::loadModule("stan_fit4mE4_Q_COv_mod", what = TRUE)
Rcpp::loadModule("stan_fit4mE4_Q_mod", what = TRUE)
Rcpp::loadModule("stan_fit4mE4_mod", what = TRUE)
Rcpp::loadModule("stan_fit4mE4c_mod", what = TRUE)
Rcpp::loadModule("stan_fit4mE4COV_mod", what = TRUE)
Rcpp::loadModule("stan_fit4mG4_Q_COV_mod", what = TRUE)
Rcpp::loadModule("stan_fit4mG4_Q_mod", what = TRUE)
Rcpp::loadModule("stan_fit4mG4_mod", what = TRUE)
Rcpp::loadModule("stan_fit4mG4c_mod", what = TRUE)
Rcpp::loadModule("stan_fit4mG4COV_mod", what = TRUE)
Rcpp::loadModule("stan_fit4mH0_Q_mod", what = TRUE)
Rcpp::loadModule("stan_fit4mH0_mod", what = TRUE)
Rcpp::loadModule("stan_fit4mH0c_mod", what = TRUE)
Rcpp::loadModule("stan_fit4mH4_Q_COV_mod", what = TRUE)
Rcpp::loadModule("stan_fit4mH4_Q_mod", what = TRUE)
Rcpp::loadModule("stan_fit4mH4_mod", what = TRUE)
Rcpp::loadModule("stan_fit4mH4c_mod", what = TRUE)
Rcpp::loadModule("stan_fit4mH4COV_mod", what = TRUE)
Rcpp::loadModule("stan_fit4mIE4_Q_COV_mod", what = TRUE)
Rcpp::loadModule("stan_fit4mIE4_Q_mod", what = TRUE)
Rcpp::loadModule("stan_fit4mIE4_mod", what = TRUE)
Rcpp::loadModule("stan_fit4mIE4c_mod", what = TRUE)
Rcpp::loadModule("stan_fit4mIE4COV_mod", what = TRUE)
Rcpp::loadModule("stan_fit4mL4_Q_COV_mod", what = TRUE)
Rcpp::loadModule("stan_fit4mL4_Q_mod", what = TRUE)
Rcpp::loadModule("stan_fit4mL4_mod", what = TRUE)
Rcpp::loadModule("stan_fit4mL4c_mod", what = TRUE)
Rcpp::loadModule("stan_fit4mL4COV_mod", what = TRUE)
Rcpp::loadModule("stan_fit4mLN4_Q_COV_mod", what = TRUE)
Rcpp::loadModule("stan_fit4mLN4_Q_mod", what = TRUE)
Rcpp::loadModule("stan_fit4mLN4_mod", what = TRUE)
Rcpp::loadModule("stan_fit4mLN4c_mod", what = TRUE)
Rcpp::loadModule("stan_fit4mLN4COV_mod", what = TRUE)
Rcpp::loadModule("stan_fit4mP4_Q_COV_mod", what = TRUE)
Rcpp::loadModule("stan_fit4mP4_Q_mod", what = TRUE)
Rcpp::loadModule("stan_fit4mP4_mod", what = TRUE)
Rcpp::loadModule("stan_fit4mP4c_mod", what = TRUE)
Rcpp::loadModule("stan_fit4mP4COV_mod", what = TRUE)
Rcpp::loadModule("stan_fit4mQE4_Q_COV_mod", what = TRUE)
Rcpp::loadModule("stan_fit4mQE4_Q_mod", what = TRUE)
Rcpp::loadModule("stan_fit4mQE4_mod", what = TRUE)
Rcpp::loadModule("stan_fit4mQE4c_mod", what = TRUE)
Rcpp::loadModule("stan_fit4mQE4COV_mod", what = TRUE)
Rcpp::loadModule("stan_fit4mSM_Q_mod", what = TRUE)
Rcpp::loadModule("stan_fit4mSM_mod", what = TRUE)
Rcpp::loadModule("stan_fit4mSMc_mod", what = TRUE)

# instantiate each stanmodel object
stanmodels <- sapply(stanmodels, function(model_name) {
  # create C++ code for stan model
  stan_file <- if(dir.exists("stan")) "stan" else file.path("inst", "stan")
  stan_file <- file.path(stan_file, paste0(model_name, ".stan"))
  stanfit <- rstan::stanc_builder(stan_file,
                                  allow_undefined = TRUE,
                                  obfuscate_model_name = FALSE)
  stanfit$model_cpp <- list(model_cppname = stanfit$model_name,
                            model_cppcode = stanfit$cppcode)
  # create stanmodel object
  methods::new(Class = "stanmodel",
               model_name = stanfit$model_name,
               model_code = stanfit$model_code,
               model_cpp = stanfit$model_cpp,
               mk_cppmodule = function(x) get(paste0("rstantools_model_", model_name)))
})
