name: build-binary-windows

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:
  
jobs:
  check-upload:
    strategy:
      fail-fast: false
      matrix:
        config:
          - {source: true, binary: true, r: '4.3'}
          - {source: false, binary: true, r: '4.2'}
          - {source: false, binary: true, r: '4.1'}
    uses: ./.github/workflows/build_binary_windows.yml
    with:
      rver: ${{ matrix.config.r}}
      build_source: ${{ matrix.config.source }}
      build_binary: ${{ matrix.config.binary }}
